name: Build ChromeOS

on:
  workflow_dispatch:

permissions: 
    contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create_release.outputs.version }}
    steps:
      - name: Create release
        id: create_release
        run: |
          GVERSION=v$(date +'%Y%m%d.%H%M')
          gh release create $GVERSION -t $GVERSION -n "Release $GVERSION"
          echo "version=$GVERSION" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        codename: [samus, rammus, shyvana, jinlon, voxel, gumboz]
    env:
      RELEASE_VERSION: ${{ needs.release.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ChromeOS
        run: |
          chmod +x build.sh
          ./build.sh ${{ matrix.codename }}

      - name: Upload File
        if: success()
        run: |
          mv chromeos/chromeos.img chromeos-${{env.RELEASE_VERSION}}-${{ matrix.codename }}.img
          ls -l
          gh release upload ${{env.RELEASE_VERSION}} chromeos-${{env.RELEASE_VERSION}}-${{ matrix.codename }}.img
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
