name: Build ChromeOS

on:
    workflow_dispatch:
        inputs:
            codename:
                type: choice
                description: |
                    Codename for ChromeOS build. 

                    # Intel Processor
                    3rd gen or older: samus
                    4th and 5th gen: leona
                    6th gen to 9th gen: shyvana
                    10th gen: jinlon
                    11th gen and newer: voxel 
                    
                    # AMD Processor
                    Ryzen: gumboz
                required: true
                options: [voxel, gumboz, jinlon, shyvana, leona, samus]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Build ChromeOS
            run: |
              chmod +x build.sh
              ./build.sh ${{ inputs.codename }}
          
          - name: Upload image
            uses: actions/upload-artifact@v4
            with:
              name: chromeos-${{ inputs.codename }}
              path: chromeos/chromeos.img
