name: Build ChromeOS

on:
    workflow_dispatch:
        inputs:
            codename:
                type: choice
                description: |
                    Codename for ChromeOS build. Check README for information on choosing a codename.
                required: true
                options: [voxel, gumboz, jinlon, shyvana, leona, samus]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            actions: write
            contents: read
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Delete workflow runs
            uses: Mattraks/delete-workflow-runs@v2
            with:
                token: ${{ github.token }}
                repository: ${{ github.repository }}
                retain_days: 7
                keep_minimum_runs: 6

          - name: Build ChromeOS
            run: |
              chmod +x build.sh
              ./build.sh ${{ inputs.codename }}
          
          - name: Upload image
            uses: actions/upload-artifact@v4
            with:
              name: chromeos-${{ inputs.codename }}
              path: chromeos/chromeos.img
