name: Build ChromeOS

on:
    push:
        branches: [main]

    workflow_dispatch:
        inputs:
            codename:
                type: choice
                description: |
                    Codename for ChromeOS build. Check README for information on choosing a codename.
                required: true
                options: [voxel, gumboz, jinlon, shyvana, leona, samus]
                default: samus
    workflow_call:
        inputs:
            target:
                required: true
                type: string

env:
    CODENAME: ${{ inputs.codename || 'samus' }}

jobs:
    build:
        runs-on: ubuntu-24.04
        permissions:
            actions: write
            contents: read
        steps:
          - name: Maximize build space
            uses: easimon/maximize-build-space@master
            with:
                root-reserve-mb: 28666
                swap-size-mb: 1024
                remove-dotnet: 'true'
                remove-android: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
          
          - name: Install git
            run: |
                sudo apt-get update
                sudo apt-get install -y git git-lfs
                sudo apt-get autopurge -y
                sudo apt-get clean

          - name: Checkout branch
            uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
            with:
                ref: ${{ inputs.target }}
                fetch-depth: '0'
                fetch-tags: 'true'
                lfs: 'true'
                submodules: 'true'
                set-safe-directory: 'true'

          - name: Delete workflow runs
            uses: Mattraks/delete-workflow-runs@v2
            with:
                token: ${{ github.token }}
                repository: ${{ github.repository }}
                retain_days: 7
                keep_minimum_runs: 6

          - name: Build ChromeOS
            run: |
              chmod +x build.sh
              ./build.sh ${{ env.CODENAME }}
          
          - name: Upload image
            uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
            with:
              name: chromeos-${{ env.CODENAME }}
              path: chromeos/chromeos.img
    
    publish:
        runs-on: ubuntu-24.04
        permissions: write-all
        needs: [build]

        steps:
            - name: Maximize build space
              uses: easimon/maximize-build-space@master
              with:
                root-reserve-mb: 28666
                swap-size-mb: 1024
                remove-dotnet: 'true'
                remove-android: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
          
            - name: Download Image
              uses: actions/download-artifact@v4
              with:
                  name: chromeos-${{ env.CODENAME }}
                  path: .
            
            - name: Install zpaq
              run: |
                  sudo apt update
                  sudo apt install -y --no-install-recommends zpaq
                  sudo apt clean

            - name: Compress image
              run: |
                  zpaq a chromeos.img.zpaq chromeos.img -m5
                  rm -f chromeos.img

            - name: Print final size
              run: |
                  ls -lh chromeos.img.zpaq

            - name: Publish release
              uses: notpeelz/action-gh-create-release@v5.0.1
              with:
                  target: ${{ inputs.target }}
                  tag: nightly
                  prerelease: true
                  strategy: replace
                  title: "Automatic build - ChromeOS-${{ env.CODENAME }}"
                  body: |
                      Automatic build ${{ env.CODENAME }}
                  files: |
                      chromeos.img.zpaq
